---
- name: Prepare
  hosts: centos
  
  tasks:

  - name: install EPEL-Release
    yum:
      name: epel-release
      state: present

  - name: Install needful soft
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - htop
      - nano
      - wget