---
- name: Prepare CentOS clear machine
  hosts: centos
  
  tasks:

  - name: Disable Firewalld service
    systemd:
      name: firewalld
      enabled: no
      state: stopped
    when: ansible_facts['distribution'] == "CentOS"

  - name: Disable UFW service
    systemd:
      name: ufw
      enabled: no
      state: stopped
    when: ansible_facts['distribution'] == "Ubuntu"

  - name: Install EPEL-Release (if Centos)
    yum:
      name: epel-release
      state: present
    when: ansible_facts['distribution'] == "CentOS"

  - name: Upgrade all packages
    yum:
      name: '*'
      state: latest
    when: ansible_facts['distribution'] == "CentOS"

  - name: Install needful soft
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - htop
      - wget
      - nano
    when: ansible_facts['distribution'] == "CentOS"