---
- name: Pre
  hosts: centos

  tasks:

  - name: install EPEL-Release
    yum:
      name: epel-release
      state: present

  - name: install pre
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - htop
      - nano
      - wget
