---
- name: Create users
  hosts: centos
  
  vars_prompt:
    - name: var_pass    
      prompt: "Enter a password for the user"    
      private: no    
      encrypt: "md5_crypt"     
      confirm: yes    
      salt_size: 7

  tasks:

  - name: add new user 
    user: name="varezhka" password="{{var_pass}}" home="/home/varezhka" shell="/bin/bash"