---
- name: Create users
  hosts: centos
  
  vars_prompt:
    - name: var_login    
      prompt: "Enter new user login:"    
      private: no
    - name: var_password    
      prompt: "Enter a password for the user"    
      private: no    
      encrypt: "md5_crypt"     
      confirm: yes    
      salt_size: 7

  tasks:

  - name: add new user 
    user: name="{{ var_login }}" password="{{ var_password }}" home="/home/{{ var_login }}" shell="/bin/bash"

- name: Packages install
  hosts: centos
  
  tasks:

  - name: Install EPEL-Release
    yum:
      name: epel-release
      state: present

  - name: Upgrade all packages
    yum:
      name: '*'
      state: latest
  
  - name: Install needful soft
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - htop
      - wget
      - nano
      - git

- name: Configure Firewalld
  hosts: centos
  
  tasks:

  - name: Open port on Firewalld
    firewalld:
      port: 5555/tcp
      permanent: true
      state: enabled

- name: Install SoftEther VPN Server
  hosts: centos

  tasks:

  - name: Install needful packages
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - readline-devel
      - openssl-devel
      - make
      - gcc
  
  - name: Clone SoftEther repository from GitHub
    git:
      repo: https://github.com/SoftEtherVPN/SoftEtherVPN_Stable.git
      dest: /tmp/softether

  - name: Configure source code
    shell: ./configure
    args:
      chdir: /tmp/softether

  - name: Compile source code
    make:
      chdir: /tmp/softether

  - name: Copy SoftEther systemd unit 
    copy: src=/tmp/softether/systemd/softether-vpnserver.service dest=/etc/systemd/system/softether-vpnserver.service remote_src=yes directory_mode=yes

  - name: Copy SoftEther Server files
    copy: src=/tmp/softether/bin/vpnserver dest=/opt remote_src=yes directory_mode=yes  

  - name: Enable and start SoftEther VPN Service
    systemd:
      state: restarted
      daemon_reload: yes
      name: softether-vpnserver.service

- name: Configure SSH
  hosts: centos
  
  tasks:

  - name: Replace config file
    copy: src=files/sshd_config dest=/etc/ssh

  - name: Reload SSHD service
    systemd:
      name: sshd
      state: reloaded