---
- name: Pre
  hosts: centos

  tasks:

  - name: install EPEL-Release
    yum:
      name: epel-release
      state: present

  - name: install pre
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - htop
      - nano
      - wget
      - nginx

  - name: Reload service nginx, in all cases
    ansible.builtin.systemd:
      name: nginx
      state: started  

  - name: open port 80
    firewalld:
      port: 80/tcp
      permanent: true
      state: enabled
