---
- name: Install Nginx
  hosts: centos
  
  tasks:

   - name: install nginx
    yum:
      name: nginx
      state: present

  - name: open port 80
    firewalld:
      port: 80/tcp
      permanent: true
      state: enabled

  - name: start nginx
    systemd:
      name: nginx
      state: restarted
      enabled: yes
