---
- name: Prepare Ubuntu clear machine
  hosts: ubuntu

  tasks:

  - name: Disable Firewalld service
    systemd:
      name: ufw
      enabled: no
      state: stopped

  - name: Upgrade all packages
    apt:
      name: '*'
      state: latest

  - name: Install needful soft
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - htop
      - wget
      - nano

