---
- name: Install Nginx
  hosts: servers
  
  tasks:

  - name: install nginx
    apt:
      name: nginx
      state: present

  - name: enable nginx
    systemd:
      name: nginx
      state: restarted
      enabled: yes
