---
- name: Install PHP-FPM
  hosts: servers
  
  tasks:

  - name: install php-fpm
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - php
      - php-common
      - php-curl
      - php-gd
      - php-mbstring
      - php-soap
      - php-xml
      - php-xmlrpc
      - php-zip
      - php-fpm
      - php-mysql
      - php-cli
      - php-ldap

  - name: enable php-fpm
    systemd:
      name: php7.4-fpm
      enabled: yes

